services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: ghcr.io/n8n-io/n8n:latest
    plan: free
    region: frankfurt
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: N8N_METRICS
        value: false
      - key: N8N_PROXY_HOPS
        value: 2
      - key: N8N_SECURE_COOKIE
        value: true
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-op6n.onrender.com/
      - key: N8N_WEBHOOK_URL
        value: https://n8n-op6n.onrender.com/
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 168
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-eu-west-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: 6543
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.qafqqbjwoiedlpwbipwo
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: true
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: N8N_HOST
        sync: false
      - key: WEBHOOK_URL
        sync: false
